name: 🔃 Refresh

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  refresh:
    name: Refresh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      - run: npm install --global json-diff
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: List Android devices
        run: |
          gcloud firebase test android models list > android_devices.txt
          gcloud firebase test android models list --format=json > android_devices.json
      - name: List iOS devices
        run: |
          gcloud firebase test ios models list > ios_devices.txt
          gcloud firebase test ios models list --format=json > ios_devices.json
      - name: Update README.md
        run: |
          echo '# Firebase Test Lab Devices [![🔃 Refresh](https://github.com/SimonMarquis/Firebase-Test-Lab-Devices/actions/workflows/refresh.yml/badge.svg)](https://github.com/SimonMarquis/Firebase-Test-Lab-Devices/actions/workflows/refresh.yml)' > README.md
          echo ''                 >> README.md
          echo '## Android'       >> README.md
          echo ''                 >> README.md
          echo '```'              >> README.md
          cat android_devices.txt >> README.md
          echo '```'              >> README.md
          echo ''                 >> README.md
          echo '## iOS'           >> README.md
          echo ''                 >> README.md
          echo '```'              >> README.md
          cat ios_devices.txt     >> README.md
          echo '```'              >> README.md
      - name: Commit changes
        run: |
          if ! git diff --quiet --exit-code -- README.md android_devices.txt android_devices.json ios_devices.txt ios_devices.json;
          then
            git config --global user.name "Simon Marquis"
            git config --global user.email "SimonMarquis@users.noreply.github.com"
            (
              echo -e "🔃$(git diff --shortstat android_devices.json ios_devices.json)\n\n"

              if ! git diff --quiet --exit-code -- android_devices.json;
              then
                git show HEAD:android_devices.json > ${{ runner.temp }}/android_devices.json
                json-diff ${{ runner.temp }}/android_devices.json android_devices.json --max-elisions=0 --output-keys=id,name
              fi

              if ! git diff --quiet --exit-code -- ios_devices.json;
              then
                git show HEAD:ios_devices.json > ${{ runner.temp }}/ios_devices.json
                json-diff ${{ runner.temp }}/ios_devices.json ios_devices.json --max-elisions=0 --output-keys=id,name
              fi
            ) | git commit README.md android_devices.txt android_devices.json ios_devices.txt ios_devices.json --file -
            git push
            echo "::notice::UPDATED"
          else
            echo "::notice::UP-TO-DATE"
          fi
